networks:
  grafana: {}

services:
  grafana:
    image: grafana/grafana:12.3.3
    ports:
      - 3000:3000
    expose:
      - '3000'
    networks:
      - grafana

  resource:
    build: .
    command: sleep 3600
    depends_on:
      - grafana
    networks:
      - grafana
