networks:
  grafana: {}
  concourse: {}

services:
  grafana:
    image: grafana/grafana:12.3.2
    ports:
      - 3000:3000
    expose:
      - '3000'
    networks:
      - grafana

  resource:
    build: .
    command: sleep 3600
    depends_on:
      - grafana
    networks:
      - grafana

  concourse-db:
    image: postgres
    ports:
      - 5432:5432
    networks:
      - concourse
    environment:
      POSTGRES_DB: concourse
      POSTGRES_USER: concourse_user
      POSTGRES_PASSWORD: concourse_pass

  concourse:
    image: concourse/concourse:7.14.3
    privileged: true
    command: quickstart
    depends_on: [concourse-db]
    ports:
      - 8080:8080
    expose:
      - 8080
    networks:
      - concourse
      - grafana
    environment:
      CONCOURSE_EXTERNAL_URL: http://localhost:8080
      CONCOURSE_POSTGRES_HOST: concourse-db
      CONCOURSE_POSTGRES_USER: concourse_user
      CONCOURSE_POSTGRES_PASSWORD: concourse_pass
      CONCOURSE_POSTGRES_DATABASE: concourse
      CONCOURSE_ADD_LOCAL_USER: admin:admin
      CONCOURSE_MAIN_TEAM_LOCAL_USER: admin
